# Generated by Django 6.0.3 on 2026-05-11 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.TextField()),
                ('url', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.TextField()),
                ('status', models.CharField(choices=[('scraped', 'scraped'), ('failed', 'failed'), ('sent', 'sent')], default='scraped', max_length=10)),
                ('linkedin_job_id', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote'), ('contract', 'Contract')], max_length=20)),
                ('job_keyword', models.TextField(blank=True, null=True)),
                ('location_preference', models.TextField(blank=True, null=True)),
                ('applied_job', models.ManyToManyField(related_name='applied_job', to='jobs.joblisting')),
                ('found_job', models.ManyToManyField(related_name='found_job', to='jobs.joblisting')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
