# Generated by Django 6.0.3 on 2026-05-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_userjobmatch_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjobmatch',
            name='company',
            field=models.CharField(blank=True, max_length=25544, null=True),
        ),
        migrations.AlterField(
            model_name='userjobmatch',
            name='title',
            field=models.CharField(blank=True, max_length=25544, null=True),
        ),
    ]
