

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: asim1111
    ports:
    - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  pgbouncer:
    image: pgbouncer/pgbouncer
    environment:
      DATABASES_HOST: db
      DATABASES_PORT: 5432
      DATABASES_USER: myuser
      DATABASES_PASSWORD: asim1111
      DATABASES_DBNAME: mydb
      PGBOUNCER_LISTEN_ADDR: 0.0.0.0
      PGBOUNCER_LISTEN_PORT: 5432
      PGBOUNCER_POOL_MODE: transaction
      PGBOUNCER_MAX_CLIENT_CONN: 1000
      PGBOUNCER_DEFAULT_POOL_SIZE: 20
    ports:
      - "5432:5432"
    depends_on:
      - db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pgbouncer
      - redis

  celery:
    build: .
    command: celery -A mysite worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - pgbouncer
      - redis

  

volumes:
  postgres_data:
