# Generated by Django 6.0.3 on 2026-05-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_likecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('like-comment', 'like-comment'), ('follow', 'follow')], max_length=20),
        ),
    ]
